/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVaultRouteImport } from './routes/app.vault'
import { Route as AppStreamRouteImport } from './routes/app.stream'
import { Route as AppPrivacyRouteImport } from './routes/app.privacy'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppGovernanceRouteImport } from './routes/app.governance'
import { Route as AppDisputeRouteImport } from './routes/app.dispute'
import { Route as AppCreditRouteImport } from './routes/app.credit'
import { Route as AppContributeRouteImport } from './routes/app.contribute'
import { Route as AppCirclesRouteImport } from './routes/app.circles'
import { Route as AppBrowseRouteImport } from './routes/app.browse'
import { Route as AppBidRouteImport } from './routes/app.bid'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppStreamRoute = AppStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppGovernanceRoute = AppGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AppRoute,
} as any)
const AppDisputeRoute = AppDisputeRouteImport.update({
  id: '/dispute',
  path: '/dispute',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditRoute = AppCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => AppRoute,
} as any)
const AppContributeRoute = AppContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesRoute = AppCirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseRoute = AppBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AppRoute,
} as any)
const AppBidRoute = AppBidRouteImport.update({
  id: '/bid',
  path: '/bid',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/bid': typeof AppBidRoute
  '/app/browse': typeof AppBrowseRoute
  '/app/circles': typeof AppCirclesRoute
  '/app/contribute': typeof AppContributeRoute
  '/app/credit': typeof AppCreditRoute
  '/app/dispute': typeof AppDisputeRoute
  '/app/governance': typeof AppGovernanceRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/stream': typeof AppStreamRoute
  '/app/vault': typeof AppVaultRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/bid': typeof AppBidRoute
  '/app/browse': typeof AppBrowseRoute
  '/app/circles': typeof AppCirclesRoute
  '/app/contribute': typeof AppContributeRoute
  '/app/credit': typeof AppCreditRoute
  '/app/dispute': typeof AppDisputeRoute
  '/app/governance': typeof AppGovernanceRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/stream': typeof AppStreamRoute
  '/app/vault': typeof AppVaultRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/bid': typeof AppBidRoute
  '/app/browse': typeof AppBrowseRoute
  '/app/circles': typeof AppCirclesRoute
  '/app/contribute': typeof AppContributeRoute
  '/app/credit': typeof AppCreditRoute
  '/app/dispute': typeof AppDisputeRoute
  '/app/governance': typeof AppGovernanceRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/stream': typeof AppStreamRoute
  '/app/vault': typeof AppVaultRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/docs'
    | '/app/admin'
    | '/app/bid'
    | '/app/browse'
    | '/app/circles'
    | '/app/contribute'
    | '/app/credit'
    | '/app/dispute'
    | '/app/governance'
    | '/app/onboarding'
    | '/app/privacy'
    | '/app/stream'
    | '/app/vault'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/app/admin'
    | '/app/bid'
    | '/app/browse'
    | '/app/circles'
    | '/app/contribute'
    | '/app/credit'
    | '/app/dispute'
    | '/app/governance'
    | '/app/onboarding'
    | '/app/privacy'
    | '/app/stream'
    | '/app/vault'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/docs'
    | '/app/admin'
    | '/app/bid'
    | '/app/browse'
    | '/app/circles'
    | '/app/contribute'
    | '/app/credit'
    | '/app/dispute'
    | '/app/governance'
    | '/app/onboarding'
    | '/app/privacy'
    | '/app/stream'
    | '/app/vault'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vault': {
      id: '/app/vault'
      path: '/vault'
      fullPath: '/app/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stream': {
      id: '/app/stream'
      path: '/stream'
      fullPath: '/app/stream'
      preLoaderRoute: typeof AppStreamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/privacy': {
      id: '/app/privacy'
      path: '/privacy'
      fullPath: '/app/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/governance': {
      id: '/app/governance'
      path: '/governance'
      fullPath: '/app/governance'
      preLoaderRoute: typeof AppGovernanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dispute': {
      id: '/app/dispute'
      path: '/dispute'
      fullPath: '/app/dispute'
      preLoaderRoute: typeof AppDisputeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/credit': {
      id: '/app/credit'
      path: '/credit'
      fullPath: '/app/credit'
      preLoaderRoute: typeof AppCreditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contribute': {
      id: '/app/contribute'
      path: '/contribute'
      fullPath: '/app/contribute'
      preLoaderRoute: typeof AppContributeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/circles': {
      id: '/app/circles'
      path: '/circles'
      fullPath: '/app/circles'
      preLoaderRoute: typeof AppCirclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/browse': {
      id: '/app/browse'
      path: '/browse'
      fullPath: '/app/browse'
      preLoaderRoute: typeof AppBrowseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bid': {
      id: '/app/bid'
      path: '/bid'
      fullPath: '/app/bid'
      preLoaderRoute: typeof AppBidRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBidRoute: typeof AppBidRoute
  AppBrowseRoute: typeof AppBrowseRoute
  AppCirclesRoute: typeof AppCirclesRoute
  AppContributeRoute: typeof AppContributeRoute
  AppCreditRoute: typeof AppCreditRoute
  AppDisputeRoute: typeof AppDisputeRoute
  AppGovernanceRoute: typeof AppGovernanceRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppStreamRoute: typeof AppStreamRoute
  AppVaultRoute: typeof AppVaultRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBidRoute: AppBidRoute,
  AppBrowseRoute: AppBrowseRoute,
  AppCirclesRoute: AppCirclesRoute,
  AppContributeRoute: AppContributeRoute,
  AppCreditRoute: AppCreditRoute,
  AppDisputeRoute: AppDisputeRoute,
  AppGovernanceRoute: AppGovernanceRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppStreamRoute: AppStreamRoute,
  AppVaultRoute: AppVaultRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
